<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { Save, ShieldAlert } from 'lucide-vue-next'
import { useRoute } from 'vue-router'
import { formatDate, request, RequestError } from '../api/client'
import StatusBadge from '../components/StatusBadge.vue'
import type { Hazard, HazardState } from '../domain'
import { useHazardStore } from '../stores/hazards'
const route=useRoute();const store=useHazardStore();const error=ref('');const owner=ref('');const action=reactive<{target_state:HazardState;reason:string}>({target_state:'handling',reason:''});const downgradeReason=ref('')
const hazard=computed(()=>store.selected)
onMounted(async()=>{const value=await store.get(String(route.params.id));owner.value=value.owner_id})
async function assign(){if(!hazard.value)return;try{await store.assign(hazard.value.id,owner.value,hazard.value.version)}catch(e){error.value=e instanceof RequestError?e.detail.message:'分派失败'}}
async function transition(){if(!hazard.value)return;try{store.selected=await request<Hazard>(`/hazards/${hazard.value.id}/transitions`,{method:'POST',headers:{'If-Match':String(hazard.value.version)},body:JSON.stringify(action)})}catch(e){error.value=e instanceof RequestError?e.detail.message:'状态更新失败'}}
async function downgrade(){if(!hazard.value)return;try{store.selected=await request<Hazard>(`/hazards/${hazard.value.id}/downgrade`,{method:'POST',headers:{'If-Match':String(hazard.value.version)},body:JSON.stringify({reason:downgradeReason.value})})}catch(e){error.value=e instanceof RequestError?e.detail.message:'降级失败'}}
</script>
<template><section class="page"><header class="page-header"><div><h1>处置详情</h1><p>查看风险依据、队列口径和当前流转边界。</p></div><div v-if="hazard" class="toolbar"><StatusBadge :value="hazard.queue"/><StatusBadge :value="hazard.state"/></div></header><div v-if="error" class="error-banner">{{ error }}</div><div v-if="hazard" class="detail-grid"><div class="panel"><div class="panel-heading"><h2>{{ hazard.title }}</h2><StatusBadge :value="hazard.risk_level"/></div><div class="panel-body"><dl class="definition"><dt>风险分</dt><dd>{{ hazard.risk_score }}</dd><dt>现场描述</dt><dd>{{ hazard.description }}</dd><dt>初始处置</dt><dd>{{ hazard.initial_action }}</dd><dt>影响范围</dt><dd>{{ hazard.impact_scopes.join('、')||'—' }}</dd><dt>升级理由</dt><dd>{{ hazard.escalation_reason||'未命中自动升级规则' }}</dd><dt>命中依据</dt><dd>{{ hazard.matched_rule_evidence.join('；')||'—' }}</dd><dt>规则版本</dt><dd>{{ hazard.matched_rule_id?`${hazard.matched_rule_id} v${hazard.matched_rule_version}`:'—' }}</dd><dt>截止时间</dt><dd>{{ formatDate(hazard.due_at) }}</dd><dt>数据版本</dt><dd>{{ hazard.version }}</dd></dl></div></div><aside style="display:grid;gap:16px;align-content:start"><div class="panel"><div class="panel-heading"><h2>处置负责人</h2></div><div class="panel-body"><div class="field"><label>负责人标识</label><input v-model="owner"/></div><div class="form-actions"><button class="button" @click="assign"><Save :size="16"/>保存分派</button></div></div></div><div class="panel"><div class="panel-heading"><h2>状态流转</h2></div><div class="panel-body"><div class="field"><label>目标状态</label><select v-model="action.target_state"><option value="handling">处理中</option><option value="pending_review">待复核</option><option value="resolved">已解除</option><option value="closed">已关闭</option></select></div><div class="field" style="margin-top:12px"><label>操作原因</label><textarea v-model="action.reason"></textarea></div><div class="form-actions"><button class="button" @click="transition">确认流转</button></div></div></div><div v-if="hazard.escalated" class="panel"><div class="panel-heading"><h2>人工降级</h2><ShieldAlert :size="17"/></div><div class="panel-body"><div class="field"><label>降级理由</label><textarea v-model="downgradeReason"></textarea></div><div class="form-actions"><button class="button secondary" @click="downgrade">降为普通处置</button></div></div></div></aside></div></section></template>
