<script setup lang="ts">
import { reactive, ref } from 'vue'
import { ClipboardCheck } from 'lucide-vue-next'
import { request, RequestError } from '../api/client'
import type { Hazard } from '../domain'
const form=reactive({hazard_id:'',version:1,passed:true,notes:'',evidence_ids:'',restore_site:false,observed_score:0,idempotency_key:crypto.randomUUID()});const result=ref<Hazard|null>(null);const error=ref('')
async function submit(){error.value='';try{result.value=await request<Hazard>(`/hazards/${form.hazard_id}/reinspections`,{method:'POST',headers:{'If-Match':String(form.version)},body:JSON.stringify({passed:form.passed,notes:form.notes,evidence_ids:form.evidence_ids.split(',').map(v=>v.trim()).filter(Boolean),restore_site:form.restore_site,observed_score:form.observed_score,idempotency_key:form.idempotency_key})})}catch(e){error.value=e instanceof RequestError?e.detail.message:'复检提交失败'}}
</script>
<template><section class="page"><header class="page-header"><div><h1>复检确认</h1><p>重点隐患只有通过复检才能解除，恢复场地前还会检查其他未关闭的重点隐患。</p></div></header><div v-if="error" class="error-banner">{{error}}</div><div v-if="result" class="success-banner">复检已记录，隐患状态更新为 {{result.state}}。</div><form class="panel" @submit.prevent="submit"><div class="panel-heading"><h2>复检结论</h2><ClipboardCheck :size="18"/></div><div class="panel-body"><div class="form-grid"><div class="field"><label>隐患标识</label><input v-model="form.hazard_id" required/></div><div class="field"><label>当前版本</label><input v-model.number="form.version" type="number" min="1"/></div><div class="field"><label>复检结果</label><select v-model="form.passed"><option :value="true">通过</option><option :value="false">未通过</option></select></div><div class="field"><label>复测风险分</label><input v-model.number="form.observed_score" type="number" min="0" max="100"/></div><div class="field full"><label>证据标识</label><input v-model="form.evidence_ids" placeholder="evidence-1, evidence-2" required/></div><div class="field full"><label>复检说明</label><textarea v-model="form.notes" required></textarea></div><div class="field full"><label><input v-model="form.restore_site" type="checkbox" style="width:auto;min-height:0;margin-right:8px"/>同时申请恢复场地</label></div></div><div class="form-actions"><button class="button"><ClipboardCheck :size="16"/>提交复检</button></div></div></form></section></template>
