<script setup lang="ts">
import { reactive, ref } from 'vue'
import { Send, Upload } from 'lucide-vue-next'
import { request, RequestError } from '../api/client'
import type { Hazard } from '../domain'
const form=reactive({site_id:'site_demo',facility_id:'facility_demo',inspection_item_id:'item-demo',risk_category_id:'risk_electrical',title:'',description:'',severity:3,likelihood:3,impact_scopes:'people',initial_action:'',idempotency_key:crypto.randomUUID()})
const file=ref<File|null>(null); const storage=ref<{storage_key:string;size_bytes:number;content_type:string}|null>(null); const saving=ref(false); const error=ref(''); const created=ref<Hazard|null>(null)
async function upload(){if(!file.value)return; const body=new FormData();body.append('file',file.value);storage.value=await request('/attachments',{method:'POST',body})}
async function submit(){saving.value=true;error.value='';created.value=null;try{if(file.value&&!storage.value)await upload();const evidence=storage.value?[{kind:'attachment',file_name:file.value?.name,content_type:storage.value.content_type,storage_key:storage.value.storage_key,size_bytes:storage.value.size_bytes,description:'巡检现场证据'}]:[];created.value=await request<Hazard>('/hazards',{method:'POST',body:JSON.stringify({...form,impact_scopes:form.impact_scopes.split(',').map(v=>v.trim()).filter(Boolean),evidence})})}catch(e){error.value=e instanceof RequestError?`${e.detail.message}（${e.detail.request_id}）`:'上报失败'}finally{saving.value=false}}
</script>
<template><section class="page"><header class="page-header"><div><h1>巡检隐患上报</h1><p>提交后系统会计算风险分、记录规则依据，并自动分流到对应处置队列。</p></div></header><div v-if="error" class="error-banner">{{ error }}</div><div v-if="created" class="success-banner">已生成隐患 {{ created.id }}，进入{{ created.queue==='focus'?'重点':'普通' }}队列。</div><form class="panel" @submit.prevent="submit"><div class="panel-heading"><h2>现场记录</h2></div><div class="panel-body"><div class="form-grid"><div class="field"><label>场地</label><input v-model="form.site_id" required /></div><div class="field"><label>设施</label><input v-model="form.facility_id" required /></div><div class="field"><label>巡检项</label><input v-model="form.inspection_item_id" required /></div><div class="field"><label>风险分类</label><input v-model="form.risk_category_id" required /></div><div class="field full"><label>隐患标题</label><input v-model="form.title" maxlength="160" required /></div><div class="field full"><label>现场描述</label><textarea v-model="form.description" required></textarea></div><div class="field"><label>严重程度</label><input v-model.number="form.severity" type="number" min="1" max="5" /></div><div class="field"><label>发生可能性</label><input v-model.number="form.likelihood" type="number" min="1" max="5" /></div><div class="field full"><label>影响范围</label><input v-model="form.impact_scopes" placeholder="people, production" /><small>多个标签使用英文逗号分隔</small></div><div class="field full"><label>初始处置</label><textarea v-model="form.initial_action" required></textarea></div><div class="field full"><label>现场证据</label><label class="button secondary" style="width:max-content"><Upload :size="16" />选择文件<input type="file" accept="image/png,image/jpeg,application/pdf,text/plain" hidden @change="file=($event.target as HTMLInputElement).files?.[0]??null;storage=null" /></label><small>{{ file?.name || '尚未选择文件' }}</small></div></div><div class="form-actions"><button class="button" :disabled="saving"><Send :size="16" />{{ saving?'正在分级':'提交并自动分级' }}</button></div></div></form></section></template>
