<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { Plus, RefreshCw } from 'lucide-vue-next'
import { request, RequestError } from '../api/client'
import type { EscalationRule } from '../domain'
const rules=ref<EscalationRule[]>([]);const error=ref('');const saved=ref('');const form=reactive({name:'',description:'',priority:100,enabled:true,minimum_score:60,minimum_level:'high',risk_category_ids:'risk_electrical',required_impact_tags:'',minimum_evidence:1,critical_facility:true,focus_sla_minutes:480,notify_after_minutes:15,renotify_every_minutes:60})
async function load(){const data=await request<{items:EscalationRule[]}>('/escalation-rules');rules.value=data.items}
async function create(){error.value='';saved.value='';try{await request('/escalation-rules',{method:'POST',body:JSON.stringify({name:form.name,description:form.description,priority:form.priority,enabled:form.enabled,condition:{minimum_score:form.minimum_score,minimum_level:form.minimum_level,risk_category_ids:form.risk_category_ids.split(',').filter(Boolean),required_impact_tags:form.required_impact_tags.split(',').filter(Boolean),minimum_evidence:form.minimum_evidence,critical_facility:form.critical_facility},focus_sla_minutes:form.focus_sla_minutes,notify_after_minutes:form.notify_after_minutes,renotify_every_minutes:form.renotify_every_minutes})});saved.value='规则已创建并以版本 1 生效';await load()}catch(e){error.value=e instanceof RequestError?e.detail.message:'保存失败'}}
onMounted(load)
</script>
<template><section class="page"><header class="page-header"><div><h1>升级规则</h1><p>规则按优先级评估，命中时同时冻结规则版本和匹配依据。</p></div><button class="button icon secondary" title="刷新规则" @click="load"><RefreshCw :size="17"/></button></header><div v-if="error" class="error-banner">{{error}}</div><div v-if="saved" class="success-banner">{{saved}}</div><div class="split"><div class="panel"><div class="panel-heading"><h2>当前生效规则</h2><span class="badge green">{{rules.length}} 条</span></div><div class="table-wrap"><table style="min-width:600px"><thead><tr><th>优先级</th><th>规则</th><th>最低分</th><th>版本</th></tr></thead><tbody><tr v-for="rule in rules" :key="rule.id"><td>{{rule.priority}}</td><td><div class="title-cell"><strong>{{rule.name}}</strong><span>{{rule.description}}</span></div></td><td>{{rule.condition.minimum_score}}</td><td>v{{rule.version}}</td></tr></tbody></table></div></div><form class="panel" @submit.prevent="create"><div class="panel-heading"><h2>新增规则</h2><Plus :size="17"/></div><div class="panel-body"><div class="form-grid"><div class="field full"><label>规则名称</label><input v-model="form.name" required/></div><div class="field full"><label>说明</label><textarea v-model="form.description" required></textarea></div><div class="field"><label>优先级</label><input v-model.number="form.priority" type="number" min="1"/></div><div class="field"><label>最低风险分</label><input v-model.number="form.minimum_score" type="number" min="0" max="100"/></div><div class="field"><label>最低等级</label><select v-model="form.minimum_level"><option value="medium">中风险</option><option value="high">高风险</option><option value="critical">紧急</option></select></div><div class="field"><label>最少证据数</label><input v-model.number="form.minimum_evidence" type="number" min="0"/></div><div class="field full"><label>风险分类</label><input v-model="form.risk_category_ids"/></div><div class="field full"><label>必须包含的影响标签</label><input v-model="form.required_impact_tags" placeholder="people, production"/></div><div class="field"><label>重点处置时限（分钟）</label><input v-model.number="form.focus_sla_minutes" type="number" min="1"/></div><div class="field"><label>再次提醒周期（分钟）</label><input v-model.number="form.renotify_every_minutes" type="number" min="1"/></div></div><div class="form-actions"><button class="button"><Plus :size="16"/>创建规则</button></div></div></form></div></section></template>
